//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.16 at 08:09:32 AM IST 
//


package com.pmli.iib.wsdlbean;

import lombok.NoArgsConstructor;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pmli.iib.wsdlbean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@NoArgsConstructor
public class ObjectFactory {

    private static final QName _SecuredWebServiceHeaderSecuredWebServiceHeader_QNAME = new QName("http://tempuri.org/", "SecuredWebServiceHeader");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pmli.iib.wsdlbean
     * 
     */

    /**
     * Create an instance of {@link QueryUpload }
     * 
     */
    public QueryUpload createQueryUpload() {
        return new QueryUpload();
    }

    /**
     * Create an instance of {@link QueryUploadResponse }
     * 
     */
    public QueryUploadResponse createQueryUploadResponse() {
        return new QueryUploadResponse();
    }

    /**
     * Create an instance of {@link SecuredWebServiceHeader }
     *
     */
    public SecuredWebServiceHeader createSecuredWebServiceHeader() {
        return new SecuredWebServiceHeader();
    }

    /**
     * Create an instance of {@link QuantumQueryUpload }
     * 
     */
    public QuantumQueryUpload createQuantumQueryUpload() {
        return new QuantumQueryUpload();
    }

    /**
     * Create an instance of {@link QuantumQueryUploadResponse }
     * 
     */
    public QuantumQueryUploadResponse createQuantumQueryUploadResponse() {
        return new QuantumQueryUploadResponse();
    }

    /**
     * Create an instance of {@link GetQueryData }
     * 
     */
    public GetQueryData createGetQueryData() {
        return new GetQueryData();
    }

    /**
     * Create an instance of {@link GetQueryDataResponse }
     * 
     */
    public GetQueryDataResponse createGetQueryDataResponse() {
        return new GetQueryDataResponse();
    }

    /**
     * Create an instance of {@link DailyDataUpload }
     * 
     */
    public DailyDataUpload createDailyDataUpload() {
        return new DailyDataUpload();
    }

    /**
     * Create an instance of {@link DailyDataUploadResponse }
     * 
     */
    public DailyDataUploadResponse createDailyDataUploadResponse() {
        return new DailyDataUploadResponse();
    }

    /**
     * Create an instance of {@link QuantumDailyDataUpload }
     * 
     */
    public QuantumDailyDataUpload createQuantumDailyDataUpload() {
        return new QuantumDailyDataUpload();
    }

    /**
     * Create an instance of {@link QuantumDailyDataUploadResponse }
     * 
     */
    public QuantumDailyDataUploadResponse createQuantumDailyDataUploadResponse() {
        return new QuantumDailyDataUploadResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecuredWebServiceHeader }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SecuredWebServiceHeader }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "SecuredWebServiceHeader")
    public JAXBElement<SecuredWebServiceHeader> createSecuredWebServiceHeaderSecuredWebServiceHeader(SecuredWebServiceHeader value) {
        return new JAXBElement<>(_SecuredWebServiceHeaderSecuredWebServiceHeader_QNAME, SecuredWebServiceHeader.class, null, value);
    }
}
