//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.16 at 08:09:32 AM IST 
//


package com.pmli.iib.wsdlbean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="QuantumDailyDataUploadResult" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quantumDailyDataUploadResult"
})
@XmlRootElement(name = "QuantumDailyDataUploadResponse")
public class QuantumDailyDataUploadResponse {

    @XmlElement(name = "QuantumDailyDataUploadResult")
    protected byte[] quantumDailyDataUploadResult;

    /**
     * Gets the value of the quantumDailyDataUploadResult property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getQuantumDailyDataUploadResult() {
        return quantumDailyDataUploadResult;
    }

    /**
     * Sets the value of the quantumDailyDataUploadResult property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setQuantumDailyDataUploadResult(byte[] value) {
        this.quantumDailyDataUploadResult = value;
    }

}
